#!/usr/bin/env python

import jsonlines
import requests,json,datetime,random,time
from api.chalicelib import utils


user_agents = [
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0',
	'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15',
	'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0',
	'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)',
	'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)',
	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36',
	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
	'Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko',
	'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727; InfoPath.1)',
	'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36',
	'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:17.0) Gecko/20100101 Firefox/17.0',
	'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; FunWebProducts; .NET CLR 1.1.4322)',
	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299',
	'Mozilla/5.0 (Windows NT 5.1; rv:33.0) Gecko/20100101 Firefox/33.0',
	'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.7.10) Gecko/20050716 Firefox/1.0.6',
	'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0)',
	'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.0.3705; .NET CLR 1.1.4322; Media Center PC 4.0)',
	'Mozilla/5.0 (Windows NT 5.1; rv:30.0) Gecko/20100101 Firefox/30.0',
	'Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0)',
	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36',
	'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0',
	'Mozilla/5.0 (Windows NT 5.1; rv:36.0) Gecko/20100101 Firefox/36.0',
	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586',
	'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
	'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9a1) Gecko/20070308 Minefield/3.0a1',
	'Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; Win 9x 4.90)',
	'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:63.0) Gecko/20100101 Firefox/63.0',
	'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; InfoPath.1; .NET CLR 2.0.50727)',
	'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.0.7) Gecko/20060909 Firefox/1.5.0.7',
	'Mozilla/4.0 (compatible; MSIE 5.0; Windows 98; DigExt)',
	'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; FunWebProducts)',
	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36',
	'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.64 Safari/537.31',
	'Mozilla/5.0 (Windows NT 6.2; WOW64; Trident/7.0; rv:11.0) like Gecko',
	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36',
	'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)',
	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36',
	'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FunWebProducts)',
	'Mozilla/4.0 (compatible; MSIE 6.0; AOL 9.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322)',
	'Mozilla/5.0 (Windows NT 6.0; rv:34.0) Gecko/20100101 Firefox/34.0',
	'Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1; 125LA; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022)',
	'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36',
	'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; Media Center PC 6.0; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 2.0.50727; .NET4.0C; .NET4.0E)',
	'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.7.8) Gecko/20050511 Firefox/1.0.4',
	'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.0.1) Gecko/20060111 Firefox/1.5.0.1',
	'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; .NET CLR 1.0.3705; .NET CLR 1.1.4322)',
	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134',
	'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.04506.30)',
	'Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1'
]

def get_opentable_availability(restaurant_id, date_arg=None, time_arg=None, num_people=2):
    """
        date format: 2018-05-22
        time format: 19:00:00

        Sample Curl Call
        ---
        curl -X POST \
          https://www.opentable.com/restaurant/profile/116614/search \
          -H 'Cache-Control: no-cache' \
          -H 'Content-Type: application/json' \
          -d '{
            "covers":2,
            "dateTime":"2018-05-22T19:00:00",
            "isRedesign":true
        }'
    """

    if not num_people:
        num_people = random.choice( [ 2, 4] )

    if not date_arg:
        when = datetime.date.today() + datetime.timedelta(days=1)
        date_arg = when.strftime('%Y-%m-%d')

    if not time_arg:
        time_arg = random.choice( [ '12:00:00', '18:00:00', '19:00:00', '19:30:00' ] )

    #url = 'http://www.pbm.com/restaurant/profile/' + restaurant_id + '/search'
    url = 'https://www.opentable.com/restaurant/profile/' + restaurant_id + '/search'

    user_agent = random.choice( user_agents )

    request_json = {
       'covers': num_people,
       'dateTime': date_arg + 'T' + time_arg,
       'isRedesign': True
    }

    proxies = {'http': 'http://5.79.66.2:13010', 'https': 'http://5.79.66.2:13010'}
    headers = { 'User-agent': user_agent }

    retries = 3
    response = None

    wrapper = {}
    wrapper['type'] = 'ot_poll'
    wrapper['id'] = str(restaurant_id) + '-' + str(time.time())
    wrapper['request'] = request_json
    wrapper['proxies'] = proxies
    wrapper['timestamp'] = utils.time_to_timestamp( int(time.time()) )
    wrapper['t'] = int(time.time())

    #response = requests.post(url, json=request_json, proxies=proxies, headers=headers, timeout=30)
    response = requests.post(url, json=request_json, headers=headers, timeout=30)
    #for i in range(retries):
    #    try:
    #        response = requests.post(url, json=request_json, proxies=proxies, headers=headers, timeout=5)
    #        break
    #    except:
    #        pass
    print(response)

    ret = None
    if response:
        try:
            ret = json.loads(response.text)
        except:
            print("json parse fail")
            pass

    wrapper['rid'] = restaurant_id
    wrapper['url'] = url
    wrapper['response'] = ret

    try:
        utils.set_node( 'ot_poll', wrapper['id'], wrapper )
    except:
        print('set_node failed, rid='+str(restaurant_id))
        pass

    return wrapper

ret = get_opentable_availability( '148396' )
print(json.dumps(ret, separators=(',', ':')), flush=True)
exit(0)

restaurants = []

with jsonlines.open('/dev/stdin') as reader:
    for rest in reader.iter(type=dict, skip_invalid=True):
        if 'rid' in rest:
            restaurants.append(rest)

while True:
    random.shuffle( restaurants )

    for rest in restaurants:

        ret = get_opentable_availability( rest['rid'] )

        ret['rest'] = {}
        for field in [ 'title', 'phone', 'adddress', 'url' ]:
            if field in rest:
                ret['rest'][field] = rest[field]

        print(json.dumps(ret, separators=(',', ':')), flush=True)

